using DTO;

namespace DAL
{
    public interface IAccountDB
    {
        int UpdateAccountByUsername(string username, double quotaCHF, int quotaFeuilles);
        Account GetAccountByUID(int UID);
        Account GetAccountByUsername(string Username);
        Account AddAccount(string Username, int CardID); // UID will be generated by SQL for PrimaryKey
    }
}